### ISSUE TITLE
SSLError: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by wenjianmuran** [wenjianmuran/Check-Assistant#30]
```
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "C:\Program Files\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 351, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 814, in _validate_conn
    conn.connect()
  File "C:\Program Files\Python35\lib\site-packages\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "C:\Program Files\Python35\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Python35\lib\ssl.py", line 377, in wrap_socket
    _context=self)
  File "C:\Program Files\Python35\lib\ssl.py", line 752, in __init__
    self.do_handshake()
  File "C:\Program Files\Python35\lib\ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\Python35\lib\ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\requests\adapters.py", line 403, in send
    timeout=timeout
  File "C:\Program Files\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 604, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Documents/GitHub/Team-Assistant/bin/night_check.py", line 122, in main
    self.get_members()
  File "D:/Documents/GitHub/Team-Assistant/bin/night_check.py", line 66, in get_members
    for cr in self.get_checkin_rank_members():
  File "D:\Documents\GitHub\Team-Assistant\bin\common.py", line 80, in get_checkin_rank_members
    for m in crm.get_page_members(page):
  File "D:\Documents\GitHub\Team-Assistant\bin\lib\shanbay\members.py", line 127, in get_page_members
    for m in self.get_page(page)['data']['ranks']:
  File "D:\Documents\GitHub\Team-Assistant\bin\lib\shanbay\members.py", line 106, in get_page
    return self.request.get(url).json()
  File "C:\Program Files\Python35\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python35\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:645)
```

**Comment by wenjianmuran** [comment]
在此之后触发这个异常
```
Resetting dropped connection: www.shanbay.com
```

**Comment by wenjianmuran** [comment]
> Requests can, on many systems, successfully handle TLS without needing any third-party libraries. However, some users will want to use a newer version of OpenSSL or enable Requests to use more advanced features. Those require some additional third-party dependencies that are strictly optional. They can be requested when installing Requests by running `pip install requests[security]`.
